#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL
#
# @type Quadrotor Wide
#
# @maintainer Julian Oes <julian@oes.ch>
#

sh /etc/init.d/rc.mc_defaults

set MIXER quad_w

param set EKF2_MAG_TYPE 1
param set EKF2_HGT_MODE 2
param set EKF2_AID_MASK 18
param set EKF2_EVP_NOISE 0.01
param set EKF2_EV_DELAY 0
param set EKF2_EV_GATE 1
param set EKF2_ACC_NOISE 20
param set EKF2_GPS_P_NOISE 0.02
param set EKF2_GPS_P_GATE 1
param set EKF2_GPS_V_NOISE 0.02
param set EKF2_GPS_V_GATE 1
#param set EKF2_OF_N_MAX 0.5
#param set EKF2_OF_N_MIN 0.35

#param set EKF2_OF_GATE 3


